language: python
script: true
python:
  - "3.7"      # current default Python on Travis CI
deploy:
  provider: pypi
  user: __token__
  password:
    secure: hqCc5E1qV1ldk0RwJ7wZcefHs6n2gTiY8A5uaNcCpv0Xpq7my+oJVndBlLl6d3EaGe35jB7dsA+CXGA3EZXtS6ybd+nJCObKnO90orqgQUqgoNmg5sE9xdtx1kB9/221baWI9Y9ooBPDTOQpmJjCctn4pznW1sPtOvjEHrkoxUkOiqk2MTmGNkljbadQrbAzalaxNuiHgrPosXY63Y7Ob0w5rY5/kiikXz1Pb4HXRV5aHAg9/ztknuL8t55vEJzE6wNu65ng+trfBIxaD26/AbSoM7Y8pNrEY8gUg8iVlXxJ9tnF/nKWRmyPlu2EUk/qgEhAqPrJMhi9KK/OoaNdGyCnuiA0J+46ihHAdBCkTLM9YnZG42Ges9LwwHzLp6E5IwCMj1zF3J0MYMow4j73sNBor6+eBR5aI1WlDwT2reg7M2gJdXfG+1VjMO9Bfl2sO3pwMpDeNsf/umO2wAF2jFrRXc3ho9eESsk/CXe9oIc3fGSCaHRrITWAMggOjSyCMQtbw+BAkm5QKBC1MRiLnIggdcppe2z3TaGXFY5ipBj5v/QzsJgDsx07tF51Sa3amvnALJsqnWSQaQHKTnnRmqvdbVo4Mo2aJp0++tejyi5s9khaNLn7LSbz3oL2awnSbv8hT/GZLf+8I388uW1bVb0AWmIFpRzeE12w7/8IBsw=
  distributions: sdist bdist_wheel
  skip_existing: true
  before_deploy: echo 'ready?'
  deploy: echo 'during deploy'
  after_deploy: echo 'post deploy'
