language: python
script: true
deploy:
  provider: pypi
  user: __token__
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGZlNmIyNGE1LTJjY2MtNDFhNy1iNWM4LTk4Mzk5YTk0ZjJlNgACOHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJwZXJ2YW5lIl19LCAidmVyc2lvbiI6IDF9AAAGIAvMFZJke5BdWIIXUdehQb8364yQ7uhToa3fZsUYbjzs
  distributions: sdist bdist_wheel
  skip_existing: true
  before_deploy: echo 'ready?'
  deploy: echo 'during deploy'
  after_deploy: echo 'post deploy'
